//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.10 at 05:43:23 PM EAT 
//


package com.craftsoftware.ProductCategorys;

import javax.xml.bind.annotation.XmlRegistry;

import com.dataaccesslayer.entity.ProductCategory;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.craftsoftware.ProductCategorys package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.craftsoftware.ProductCategorys
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAllProductCategorysResponse }
     * 
     */
    public GetAllProductCategorysResponse createGetAllProductCategorysResponse() {
        return new GetAllProductCategorysResponse();
    }

    /**
     * Create an instance of {@link ProductCategory }
     * 
     */
    public ProductCategory createProductCategory() {
        return new ProductCategory();
    }

    /**
     * Create an instance of {@link GetProductCategoryRequest }
     * 
     */
    public GetProductCategoryRequest createGetProductCategoryRequest() {
        return new GetProductCategoryRequest();
    }

    /**
     * Create an instance of {@link GetProductCategoryResponse }
     * 
     */
    public GetProductCategoryResponse createGetProductCategoryResponse() {
        return new GetProductCategoryResponse();
    }

    /**
     * Create an instance of {@link DeleteProductCategoryRequest }
     * 
     */
    public DeleteProductCategoryRequest createDeleteProductCategoryRequest() {
        return new DeleteProductCategoryRequest();
    }

    /**
     * Create an instance of {@link GetAllProductCategorysRequest }
     * 
     */
    public GetAllProductCategorysRequest createGetAllProductCategorysRequest() {
        return new GetAllProductCategorysRequest();
    }

    /**
     * Create an instance of {@link CreateProductCategoryResponse }
     * 
     */
    public CreateProductCategoryResponse createCreateProductCategoryResponse() {
        return new CreateProductCategoryResponse();
    }

    /**
     * Create an instance of {@link UpdateProductCategoryResponse }
     * 
     */
    public UpdateProductCategoryResponse createUpdateProductCategoryResponse() {
        return new UpdateProductCategoryResponse();
    }

    /**
     * Create an instance of {@link DeleteProductCategoryResponse }
     * 
     */
    public DeleteProductCategoryResponse createDeleteProductCategoryResponse() {
        return new DeleteProductCategoryResponse();
    }

    /**
     * Create an instance of {@link CreateProductCategoryRequest }
     * 
     */
    public CreateProductCategoryRequest createCreateProductCategoryRequest() {
        return new CreateProductCategoryRequest();
    }

    /**
     * Create an instance of {@link CreateProductCategory }
     * 
     */
    public CreateProductCategory createCreateProductCategory() {
        return new CreateProductCategory();
    }

    /**
     * Create an instance of {@link UpdateProductCategoryRequest }
     * 
     */
    public UpdateProductCategoryRequest createUpdateProductCategoryRequest() {
        return new UpdateProductCategoryRequest();
    }

}
