//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.10 at 05:43:23 PM EAT 
//


package com.craftsoftware.Bills;

import javax.xml.bind.annotation.XmlRegistry;

import com.craftsoftware.models.BillUpdateInfo;

/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.craftsoftware.Bills package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.craftsoftware.Bills
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAllBillsResponse }
     * 
     */
    public GetAllBillsResponse createGetAllBillsResponse() {
        return new GetAllBillsResponse();
    }

    /**
     * Create an instance of {@link Bill }
     * 
     */
    public BillUpdateInfo createBill() {
        return new BillUpdateInfo();
    }

    /**
     * Create an instance of {@link GetBillRequest }
     * 
     */
    public GetBillRequest createGetBillRequest() {
        return new GetBillRequest();
    }

    /**
     * Create an instance of {@link GetBillResponse }
     * 
     */
    public GetBillResponse createGetBillResponse() {
        return new GetBillResponse();
    }

    /**
     * Create an instance of {@link DeleteBillRequest }
     * 
     */
    public DeleteBillRequest createDeleteBillRequest() {
        return new DeleteBillRequest();
    }

    /**
     * Create an instance of {@link GetAllBillsRequest }
     * 
     */
    public GetAllBillsRequest createGetAllBillsRequest() {
        return new GetAllBillsRequest();
    }

    /**
     * Create an instance of {@link CreateBillResponse }
     * 
     */
    public CreateBillResponse createCreateBillResponse() {
        return new CreateBillResponse();
    }

    /**
     * Create an instance of {@link UpdateBillResponse }
     * 
     */
    public UpdateBillResponse createUpdateBillResponse() {
        return new UpdateBillResponse();
    }

    /**
     * Create an instance of {@link DeleteBillResponse }
     * 
     */
    public DeleteBillResponse createDeleteBillResponse() {
        return new DeleteBillResponse();
    }

    /**
     * Create an instance of {@link CreateBillRequest }
     * 
     */
    public CreateBillRequest createCreateBillRequest() {
        return new CreateBillRequest();
    }

    /**
     * Create an instance of {@link CreateBill }
     * 
     */
    public CreateBill createCreateBill() {
        return new CreateBill();
    }

    /**
     * Create an instance of {@link UpdateBillRequest }
     * 
     */
    public UpdateBillRequest createUpdateBillRequest() {
        return new UpdateBillRequest();
    }

}
